version: '3.6'

services:
  alglang-app:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: alglang
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#{$UID}
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    networks:
      backend:
        aliases:
          - app
    depends_on:
      - alglang-db

  alglang-db:
    image: mariadb:10.4
    container_name: alglang-db
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=secret
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      backend:
        aliases:
          - alglang-db

networks:
  backend:
    name: backend-network
