name: Deploy
on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install npm dependencies with yarn
        run: yarn install --frozen-lockfile

      - name: Build javascript
        run: yarn prod

      - name: Delete node_modules
        run: rm -rf node_modules

      - name: Delete storage so they don't overwrite permissions
        run: rm -rf storage bootstrap/cache

      - name: Upload to server
        uses: appleboy/scp-action@master
        with:
          host: ssh.phx.nearlyfreespeech.net
          username: ${{ secrets.NFSN_USERNAME }}
          password: ${{ secrets.NFSN_PASSWORD }}
          port: 22
          source: "."
          target: ${{ secrets.NFSN_DIR }}

      - name: Perform server maintenance
        uses: appleboy/ssh-action@master
        env:
          NFSN_DIR: ${{ secrets.NFSN_DIR }}
        with:
          host: ssh.phx.nearlyfreespeech.net
          username: ${{ secrets.NFSN_USERNAME }}
          password: ${{ secrets.NFSN_PASSWORD }}
          port: 22
          envs: NFSN_DIR
          script_stop: true
          script: |
            # Move to the correct directory
            cd "$NFSN_DIR"

            # Install composer dependencies, but don't try to run the script
            # afterword because it will segfault
            composer install -o --no-dev --no-scripts

            # Run the postinstall script manually
            php artisan package:discover

            # Migrate any new migrations
            php artisan migrate --force
